### ISSUE TITLE
救済対応（ルーンナイト、ギロチンクロス、両手装備、弱スキルなど）

### ISSUE THREAD

**Issue by rhutaba** [h3poteto/sagisame#125]
アイテム	対応内容（素案）
----------------------------------------
両手剣		MDEF
両手槍		MDEF
両手斧		MDEF
カタール	DEFまたはMDEF
弓		片手
ミストレス	固定詠唱減少
アモン		FP＋900％、MS＋25％

またはキーとなるアクセサリーで特定の職や型を救済するなど

**Comment by rhutaba** [comment]
○両手剣（課金アイテムを除きだいたい）
DEF +15
MDEF +15

○両手槍（課金アイテムを除きだいたい）
DEF +15
MDEF +15

○両手斧（課金アイテムを除きだいたい）
DEF +15
MDEF +15

○弓（課金アイテムを除きだいたい）
DEF +15
MDEF +15

○矢
ATK +100%
（状態異常系の矢はATK1→ATK30）

○ミストレスカード
ジェム消費無し
詠唱時間 -10%
固定詠唱 -50%
ディレイ -5%
bonus bNoGemStone,0; bonus2 bFixCastrate,-50,1; bonus bCastrate,-10; bonus bSkillDelayRate,-5;


○アモンラーカード
ステータスALL+2
純粋なINT99が以下の場合、キリエエレイソンが3%の確率で発動。
純粋なINTが100以上の場合、キリエエレイソンが10%の確率で発動。
ファイアーピラーのダメージが+900%
メテオストームのダメージが+50%
詠唱時間 -20%
固定詠唱 -10%

bonus bStr,2; bonus bAgi,2; bonus bVit,2; bonus bInt,2; bonus bDex,2; bonus bLuk,2; 
if(readparam(bInt)<99){
	bonus3 bRevAutoSelfSpell,73,10,300;
}
else{
	bonus3 bRevAutoSelfSpell,73,10,1000;
}
bonus2 bAddSkillDamageRate,80,900;
bonus2 bAddSkillDamageRate,83,25;
bonus bCastrate,-20;
bonus2 bFixCastrate,-10,1;


○回復アイテム（501～599）
重量を半減

○ポーション
HPとSPの回復量が増加
HPとSPを両方回復するように修正
例）
　赤P　itemheal rand(165,185),rand(30,40);
　紅P　itemheal rand(225,265),rand(25,40);
　黄P　itemheal rand(295,355),rand(10,30);
　白P　itemheal rand(445,525),rand(5,25);
　青P　itemheal rand(10,100),rand(90,120);
　ﾏｽﾃﾗ itemheal rand(430,610),0;

**Comment by h3poteto** [comment]
これから製薬するであろうスリムポーション系も同様にグレードアップしたい（重量半減＋効果増大）

**Comment by rhutaba** [comment]
織り込み済みですよ
