### ISSUE TITLE
続・黄箱内の重複アイテムの削除

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/sagisame#139]
- オークヒーロの兜
- エンジェリング帽

などは複数個定義されている．item_db_add.txtを見ると，微妙に効果が違うので，相談の上，片方だけを残したら良いんじゃないだろうか．

**Comment by h3poteto** [comment]
整理したいものリスト

- オークヒーローの兜
- 大型オークヒーローの兜の箱
- エンジェリング帽
- マジックアイズ
- オークヒーローの兜Rの箱
- たれ慰める者の箱

**Comment by h3poteto** [comment]
`5094,Orc_Hero_Helm,オークヒーローの兜,11,500000,,900,,5,,0,991944702,2,768,,55,178,1,{},{ bonus bStr,2; bonus bVit,1; }`
`5224,Orc_Hero_Helm_TW,オークヒーローの兜,11,20,,900,,5,,0,991944702,2,768,,55,178,1,{},{ bonus bStr,2; bonus bVit,1; bonus bMaxHPrate,10; }`
値段とボーナスのHP効果がちょっと違うらしい

**Comment by rhutaba** [comment]
ROROの本鯖情報みても5224の方が存在してない。どういうことなんだか判断できないｗ

**Comment by h3poteto** [comment]
たぶんaurigaの元となるデータのどっかに入っていたんだろうけど……まぁ普通にボーナス乗ってる方を採用しますかね．

**Comment by h3poteto** [comment]
`5132,Angeling_Hat,エンジェリング帽,4,20,,700,,5,,0,1000333311,2,256,,38,204,1,{},{ bonus2 bSubRace,Rct_Human,10; bonus2 bMagicSubRace,Rct_Human,10; }`
`5334,Angeling_Wanna_Fly,エンジェリング帽,4,20,,700,,0:2,,0,1000333311,2,256,,38,348,,{},{ bonus bLuk,2; }`
こちらもボーナス乗ってる方を採用するか

**Comment by h3poteto** [comment]
`5138,Magic_Eyes,マジックアイズ,4,,,300,,3:5,,0,1000333311,2,256,,30,209,1,{},{ bonus bCastRate,-10; }`
`5639,F_Magic_Eyes,マジックアイズ,4,,,300,,1,,0,1000333311,2,256,,30,209,1,{},{ bonus bCastRate,-10; bonus bMdef,5; bonus bUseSPrate,20; }`
マジックアイズは結構変わるな……．そもそも片方はスロットついてんじゃないか……？

**Comment by h3poteto** [comment]
クライアントでは5639は「進化したマジックアイズ」と表示される．しかしスロットは実装されていないようで，カードはさせない．

**Comment by rhutaba** [comment]
進化したマジックアイズをGoogle検索すると笑う

**Comment by h3poteto** [comment]
マジックアイズ（卑猥）

**Comment by h3poteto** [comment]
マジックアイズ[1]（意味深だな……

**Comment by h3poteto** [comment]
進化したマジックアイズ[2]

**Comment by h3poteto** [comment]
ROもヤバイ名前をつけてしまったな……

**Comment by rhutaba** [comment]
定義はされてるけど本鯖じゃ出てないアイテムな可能性。Grfにはデータが入っていたので、誰かがDBに入れ込んだのではと憶測してみる。

**Comment by h3poteto** [comment]
だなーどうしようか
たぶんunknownアイテムにはならないとは思うけど．

**Comment by rhutaba** [comment]
基本強い方のこすのでいいんじゃないかな、っておもーの

**Comment by h3poteto** [comment]
うぃす
