### ISSUE TITLE
カプラのペコ，ファルコン貸出が転生に対応していない

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/sagisame#64]
職種判定で弾かれる

**Comment by rhutaba** [comment]
`	//プレイヤーの職業チェック
	switch(Class) {
	  case Job_Knight:
	  case Job_RuneKnight:
	  case Job_Crusader:
	  case Job_RoyalGuard:
`
のswitch(Class)が間違えていた模様。正解はswitch(Job)で、参考は以下のとおり。

["Job"の定義](https://github.com/h3poteto/sagisame/blob/master/db/const.txt#L354)
[switch文での実例](https://github.com/h3poteto/sagisame/blob/master/script/original/npc_original_jobchanger.txt#L211)
