### ISSUE TITLE
ペコ，ファルコン貸出の，騎乗判定が間違っている

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/sagisame#69]
徒歩で行っても「すでに騎乗している」と言われる

**Comment by rhutaba** [comment]
騎乗でいくと降ろされる

**Comment by h3poteto** [comment]
悲しすぎるｗｗ

**Comment by rhutaba** [comment]
鷹のレンタルが「あなたのジョブでは利用することができません」となる。

**Comment by rhutaba** [comment]
## 現状
ペコペコ（ナイト、パラ）と、グリフォンはcheckriding()でOKらしい。
ペコペコ（ナイト、パラ）と、グリフォンはsetridingでOKらしい。
ドラゴン（ルーンナイト）は、checkdragon()を掛けないとダメらしい。
ドラゴン（ルーンナイト）は、setdragonを掛けないとダメらしい。

`		if(checkriding()) {`
`			mes "[カプラ職員]";`
`			mes "すでに騎乗していますよ。";`
`			mes "またご利用くださいませ。";`
`			goto L_EXIT;`
`		}`

## 修正予定
- ルーンナイトのドラゴンのcaseだけ独自に記述する。
- ペコとグリフォンのcaseは共通で記述する。
- ファルコンのレンタルでケアレスミスが2件あったため修正。カッコ位置とsetfalconの記述

## リファレンス
`		checkcart関数`
`			checkcart()`
`			カートを所持していたら１を、そうでなければ０を返します`
`		checkfalcon関数`
`			checkfalcon()`
`			鷹といっしょにいたら１を、そうでなければ０を返します`
`		checkriding関数`
`			checkriding()`
`			ペコペコに乗っていたら１を、そうでなければ０を返します`
`		checkdragon関数`
`			checkdragon()`
`			ドラゴンに乗っていたら１を、そうでなければ０を返します`
`		checkgear関数`
`			checkgear()`
`			魔道ギアに乗っていたら１を、そうでなければ０を返します`
