### ISSUE TITLE
コモドのMHマップで，クライアントがクラッシュする場合がある

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/sagisame#71]
cmd_fild08

おそらくR化後のmobデータを呼んでいるためである．
現状この鯖はR化のフラグをオフにしてコンパイルしているため，mobのデータは，db/addon/mob_db_add.txtから読みだしており，そこにはR化後のmobは載っていない．

**Comment by rhutaba** [comment]
本鯖の蔵データを最新(2016/07/18)にしてみても落ちるのでサーバ側の設定っぽいことを確認。

**Comment by rhutaba** [comment]
## 確認済み(OK)
- 転生二次DOPたち全種類
- バコワナ（ただしドロップは不明、固定ダメ1で倒せない）
- 植えた実験動物
- スカラバのザコ(剛角、卵)
- ボイルドライス
- クリスマス系MOB

## 未確認(NG)
- バコワナ系のザコMOB未確認
- オーラポリン
- イベントバフォメット
- 王の死骸
- ヒュージリング

**Comment by rhutaba** [comment]
上記未確認MOBをコメントアウトとする対応をしてみたけどみたけどどうだろうか？
タブ位置も綺麗に修正した内容で、とりあえずコミットしますね。

参考情報
### mob_db.txtの定義域
`2082,G_PIRANHA,ピラニア,`
2083番以降はテキスト上に記載されていない。

### cmd_fild08.gatで確認したmob達
`2221,RANDEL,ランデル=ロレンス`
`2222,FLAMEL,エミュール=プラメール`
`2223,CELIA,セリア=アルデ`
`2224,CHEN,チェン=リウ`
`2225,GERTIE,ガーティー=ウー`
`2226,ALPHOCCIO,アルフォシオ=バジル`
`2227,TRENTINI,トレンティーニ,154,25`
`2228,G_RANDEL,ランデル=ロレンス,150`
`2229,G_FLAMEL,エミュール=プラメール`
`2230,G_CELIA,セリア=アルデ,150,1687`
`2231,G_CHEN,チェン=リウ`
`2232,G_GERTIE,ガーティー=ウー`
`2233,G_ALPHOCCIO,アルフォシオ=バジル`
`2234,G_TRENTINI,トレンティーニ`

**Comment by rhutaba** [comment]
確かこいつらが悪さしてた気がする。
別の機会で召喚したら、バグ原因を探るということにして本イシューはクローズしたい。

オーラポリン（怪しい）
イベントバフォメット（単に未確認、大丈夫そう）
王の死骸（怪しい）
ヒュージリング（怪しい）

**Comment by h3poteto** [comment]
怪しいやつは除外しようか．というか現状で攻略不可能なマップになっているので結構むずいよな．

**Comment by rhutaba** [comment]
記載がたりなかった。下記は除外済みなので、コモドマップは現状エラー落ちしないです。

オーラポリン（怪しい）
イベントバフォメット（単に未確認、大丈夫そう）
王の死骸（怪しい）
ヒュージリング（怪しい）

**Comment by h3poteto** [comment]
なるほど
