### ISSUE TITLE
濃縮エルオリの箱から出現するアイテム数が少ないため調整

### ISSUE THREAD

**Issue by rhutaba** [h3poteto/sagisame#93]
個数増やすよ！

【変更後】
- 濃縮エルニウムの箱 id:12920
12920,Enriched_Elunium_Box,濃縮エルニウムの箱,2,,,10,,,,,1000333311,2,,,,,,{ getitem 7619,20; },{}

- 濃縮オリデオコンの箱 id:12921
12921,Enriched_Oridecon_Box,濃縮オリデオコンの箱,2,,,10,,,,,1000333311,2,,,,,,{ getitem 7620,20; },{}

【変更前】
- 濃縮エルニウムの箱 id:12920
12920,Enriched_Elunium_Box,濃縮エルニウムの箱,2,,,10,,,,,1000333311,2,,,,,,{ getitem 7619,1; },{}

- 濃縮オリデオコンの箱 id:12921
12921,Enriched_Oridecon_Box,濃縮オリデオコンの箱,2,,,10,,,,,1000333311,2,,,,,,{ getitem 7620,1; },{}

**Comment by h3poteto** [comment]
あーこれ箱あるのはいいねー

**Comment by rhutaba** [comment]
ただし箱はボスから出る

**Comment by h3poteto** [comment]
よいんでは
